-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("XCURSOR_SIZE", "24")

-- Settings
hl.config({
    decoration = {
        active_opacity = 0.85,
        blur = {
            special = false,
        },
        dim_around = 0.4,
        dim_special = 0.2,
        rounding = 25,
        rounding_power = 2.0,
    },
    general = {
        border_size = 0,
        col = {
            active_border = "0xffffffff",
            inactive_border = "0xff77767b",
        },
        gaps_out = 12,
        snap = {
            enabled = true,
        },
    },
    gestures = {
        workspace_swipe_cancel_ratio = 0.4,
        workspace_swipe_invert = false,
        workspace_swipe_min_speed_to_force = 50,
        workspace_swipe_use_r = false,
    },
    input = {
        accel_profile = "flat",
        kb_options = "caps:escape",
        mouse_refocus = true,
        natural_scroll = false,
        sensitivity = 0.5,
        touchpad = {
            clickfinger_behavior = true,
            disable_while_typing = false,
            middle_button_emulation = true,
            natural_scroll = false,
            scroll_factor = 0.5,
        },
    },
    misc = {
        key_press_enables_dpms = false,
        mouse_move_enables_dpms = false,
    },
})

-- Monitors
hl.monitor({
    output = "eDP-1",
    disabled = false,
    mode = "2560x1600@60.00Hz",
    position = "0x0",
    scale = 1.33,
    cm = "srgb",
})

-- Keybinds
hl.unbind("SUPER + 1")
hl.bind("SUPER + 1", hl.dsp.focus({ workspace = 1 }))
hl.unbind("SUPER + 2")
hl.bind("SUPER + 2", hl.dsp.focus({ workspace = 2 }))
hl.unbind("SUPER + 3")
hl.bind("SUPER + 3", hl.dsp.focus({ workspace = 3 }))
hl.unbind("SUPER + 4")
hl.bind("SUPER + 4", hl.dsp.focus({ workspace = 4 }))
hl.unbind("SUPER + 5")
hl.bind("SUPER + 5", hl.dsp.focus({ workspace = 5 }))
hl.unbind("SUPER + 6")
hl.bind("SUPER + 6", hl.dsp.focus({ workspace = 6 }))
hl.unbind("SUPER + 7")
hl.bind("SUPER + 7", hl.dsp.focus({ workspace = 7 }))
hl.unbind("SUPER + 8")
hl.bind("SUPER + 8", hl.dsp.focus({ workspace = 8 }))
hl.unbind("SUPER + 9")
hl.bind("SUPER + 9", hl.dsp.focus({ workspace = 9 }))
hl.unbind("SUPER + 0")
hl.bind("SUPER + 0", hl.dsp.focus({ workspace = 10 }))
hl.unbind("SUPER + SHIFT + 0")
hl.bind("SUPER + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))
hl.unbind("SUPER + SHIFT + 9")
hl.bind("SUPER + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.unbind("SUPER + SHIFT + 8")
hl.bind("SUPER + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.unbind("SUPER + SHIFT + 7")
hl.bind("SUPER + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.unbind("SUPER + SHIFT + 5")
hl.bind("SUPER + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.unbind("SUPER + SHIFT + 6")
hl.bind("SUPER + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.unbind("SUPER + SHIFT + 4")
hl.bind("SUPER + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.unbind("SUPER + SHIFT + 2")
hl.bind("SUPER + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.unbind("SUPER + SHIFT + 3")
hl.bind("SUPER + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.unbind("SUPER + SHIFT + 1")
hl.bind("SUPER + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.unbind("SUPER + SHIFT + S")
hl.bind("SUPER + SHIFT + S", hl.dsp.exec_cmd("hyprmod"))
hl.unbind("SUPER + Z")
hl.bind("SUPER + Z", hl.dsp.exec_cmd("Plexamp.AppImage --dissable-secomp-filter-sandbox"))
hl.unbind("SUPER + SHIFT + CTRL + D")
hl.bind("SUPER + SHIFT + CTRL + D", hl.dsp.exec_cmd("discord"))
hl.unbind("SUPER + F11")
hl.bind("SUPER + F11", hl.dsp.window.fullscreen())
hl.unbind("SUPER + X")
hl.bind("SUPER + X", hl.dsp.exec_cmd("steam"))
hl.unbind("SUPER + Tab")
hl.bind("SUPER + Tab", hl.dsp.focus({ workspace = "previous" }))
hl.unbind("SUPER + G")
hl.bind("SUPER + G", hl.dsp.workspace.toggle_special(""))
hl.unbind("SUPER + SHIFT + G")
hl.bind("SUPER + SHIFT + G", hl.dsp.window.move({ workspace = "special" }))
hl.unbind("SUPER + SHIFT + Tab")
hl.bind("SUPER + SHIFT + Tab", hl.dsp.window.move({ workspace = "previous" }))
hl.unbind("SUPER + O")
hl.bind("SUPER + O", hl.dsp.exec_cmd("obsidian"))
hl.unbind("SUPER + R")
hl.bind("SUPER + R", hl.dsp.exec_cmd("readest"))
