--enable-proposed-api=GitHub.copilot-chat
--enable-proposed-api=ms-python.debugpy
--enable-proposed-api=ms-python.python
--enable-proposed-api=ms-python.vscode-pylance
--enable-proposed-api=ms-python.vscode-python-envs
--enable-proposed-api=ms-vscode.cpptools
--enable-proposed-api=ms-vscode.remote-explorer
--enable-proposed-api=ms-vscode-remote.remote-ssh
--enable-proposed-api=openai.chatgpt
--enable-proposed-api=vscode.mermaid-markdown-features
