-- Generated by matugen
return {
	colors = {
		bg = "{{colors.surface_container.default.hex}}",
		fg = "{{colors.on_surface.default.hex}}",
		primary = "{{colors.primary.default.hex}}",
	},
	-- Add more mappings based on matugen wiki
}
